# Generated by Django 4.0.5 on 2022-07-24 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_artists_remove_user_usertype_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='artists',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='songs',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='songs',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_likers', to='music.songs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_liked_songs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_followers', to='music.artists')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_artists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
