# Generated by Django 4.0.5 on 2022-07-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_genre_alter_songs_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='length',
            field=models.TimeField(null=True),
        ),
    ]
